# Generated by Django 4.2.5 on 2023-10-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'Cloth'), (3, 'Shoes')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdetail',
            field=models.CharField(max_length=300, verbose_name='Product Name'),
        ),
    ]
