# Generated by Django 4.2.5 on 2023-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0009_alter_products_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Product Name'),
        ),
    ]
