# Generated by Django 4.2.5 on 2023-11-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0014_alter_products_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pdetail',
            field=models.CharField(max_length=50000, verbose_name='Product Detail'),
        ),
    ]
